### ISSUE TITLE
Are you trying to arbitrage too ?

### ISSUE THREAD

**Issue by shivekkhurana** [Pankaj-Baranwal/coinsecure-bot#3]
:P

**Comment by Pankaj-Baranwal** [comment]
Trying to! Not very good at it though.

**Comment by shivekkhurana** [comment]
All the best bro :)

On 28 Nov 2017 9:47 p.m., "Pankaj" <notifications@github.com> wrote:

Trying to! Not very good at it though.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Pankaj-Baranwal/coinsecure-bot/issues/3#issuecomment-347576403>,
or mute the thread
